초대하고 싶은사람의 
깃허브상의 id라고하면
개발자 각자가 깃허브에 가입했을때의 id 라는 말인가?


Command: git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks ls-remote C:\Users\kj022\Documents\git4_collation\sourcetree\b
출력: 
오류: fatal: 'C:\Users\kj022\Documents\git4_collation\sourcetree\b' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Sourcetree determined this URL is in an unsupported format.
Command: perl.exe C:\Users\kj022\AppData\Local\SourceTree\app-3.4.22\tools\svn.pl info C:\Users\kj022\Documents\git4_collation\sourcetree\b
출력: 
오류: System.ComponentModel.Win32Exception: 지정된 파일을 찾을 수 없습니다

이오류의 원인? 조치방법?



git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks fetch --no-tags origin

git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks pull origin master
fatal: couldn't find remote ref master
오류가 나면서 완료됨. 
sourcetree에서 pull 수행시 발생한 상기 오류의 원인? 조치방법?



git -c filter.lfs.smudge= -c filter.lfs.required=false -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks clone C:\Users\kj022\Documents\git4_collation\sourcetree\b C:\Users\kj022\Documents\b
fatal: destination path 'C:\Users\kj022\Documents\b' already exists and is not an empty directory.
오류가 나면서 완료됨. 
sourcetree에서 클론버튼을 누르는 순간 위의 메시지가 
나온다  원인및 조치 방법은?


소스트리에서 
clone 대상으로 선택한 폴더가
"git저장소가 아니다"로나와서 
git init를 수행해주니  .git파일이 
해당폴더에 생겼다.
그리고 그 폴더를 지정하고 클론했더니
아래 메시지가 나온다
어떻게 조치해야하는가?
git -c filter.lfs.smudge= -c filter.lfs.required=false -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks clone C:\Users\kj022\Documents\git4_collation\sourcetree\b C:\Users\kj022\Documents\b
fatal: destination path 'C:\Users\kj022\Documents\b' already exists and is not an empty directory.
오류가 나면서 완료됨. 
